MoralesMatiasEzequiel/pf-libreria-FRONT

- src/components/common/Nav/Nav.jsx
- src/components/common/Nav/Nav.module.css
creo la nav principal, luego con estilos se hace responsive y puede mejorar
> creo nav sin estilos

- package-lock.json
- package.json
- src/components/views/Home/Home.jsx
- src/components/views/Shop/Products/Products.jsx
- src/index.js
- src/redux/productActions.js
- src/redux/productSlice.js
- src/redux/store.js
ya caen de por si los products en el reducer automaticamente ( pero falta que lucas agrege al home el dispatch para que se carguen)
> creación de reducer

- .gitignore
- src/components/common/Menu/Menu.jsx
- src/components/views/Shop/Products/Products.jsx
YA NO SE SUBE EL NODE_MODULES / LO AGREGUÉ AL GITIGNORE
> prueba no se suba el node

- src/App.js
Loading funcionando, sin estilo.
> loading ok

- src/components/views/Shop/Filters/Filters.jsx
- src/components/views/Shop/Filters/Filters.module.css
- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/Shop.jsx
- src/redux/productActions.js
- src/redux/productSlice.js
de menor a mayor y vice versa, de a a la z y vice versa y diseño responsivo.
> Ordenadores por alfabetico y prrecio

- src/components/common/SearchBar/SearchBar.jsx
- src/components/views/Shop/Products/Products.jsx
- src/redux/productSlice.js
modifique un poco el redux de los ordenamientos para que pueda ordenar las cards traidas por nombre. NOTA -- hay un diley que toca chequear, es por el useEffect, pero no es nada  que no permita correr la pagina
> render por nombre

- src/App.js
- src/components/common/Modals/ModalCart/ModalCart.jsx
- src/components/common/Modals/ModalCart/ModalCart.module.css
- src/components/views/Cart/Cart.jsx
- src/components/views/Shop/Detail/Detail.jsx
> Pop up Cart

- src/components/common/SearchBar/SearchBar.jsx
- src/components/common/SearchBar/SearchBar.module.css
no esta 100% responsive. Cuando este listo las categorias, ahi si se puede hacer responsive
> searchBar con estilos

- src/components/views/Shop/Products/Products.jsx
solucioné el paginado y el conflicto que tenia con la mano que metrio sofia y ya anda rte bien nais candela
> solucionamiento de la app

- src/components/views/Shop/SideFilters/Side.jsx
- src/redux/productSlice.js
cuando0 agregas un orden o un filtro. vuelve a la pagina 1 (los erroees del pi eran que te quedabas en la pagina "ejemplo " 5 y no habia nada ahí..... ya lo reesolví
> reinicio de pagina al ordenar y o filtar. (corregí errores)

- src/components/views/Shop/SideFilters/Side.jsx
se mapean con éxito, hasta cambiando de categorias, falta darle el evento onclick que despache la action ( que no se como se hace) alguien bondadoso que me ayude ?
> se mapean las marcas con éxito, falta el evento dispatch

- src/components/views/Home/Home.jsx
- src/components/views/Home/Home.module.css
- src/redux/productActions.js
- src/redux/productSlice.js
carousel sin terminar, hardcodeado por ahora para que el home tenga algo
> carousel sin terminar

- src/redux/productSlice.js
si no hgay na no muestra na, y si si hayalgo muestra algo. NISE
> manejo de errorr al buscar por name

- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/Products/Products.module.css
- src/components/views/Shop/Shop.jsx
- src/components/views/Shop/Shop.module.css
solo mejoré el estilizado para que se renderizen mejor a la vista
> ajustado del estilizado de las cards

- src/components/views/Shop/Products/Products.jsx
renderiza bien las cards cuando se escogen marcas. con paginado segun la cantidad de cartas mostradas en pantalla.
único problema detectado: si estas en pag >1 y deseleccionas las suficientes marcas como para que hayan menos de 12 productos , se queda en la pagina 2.(deberia irse a la pagina1 automaticamente).
> buen renderizado por marca y paginado

- src/components/views/Shop/Filters/Filters.jsx
- src/components/views/Shop/Filters/Filters.module.css
- src/components/views/Shop/Shop.jsx
arriba de marca sale la marca seleccionada
> sale que marca seleccionaste

- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/Products/Products.module.css
- src/components/views/Shop/SideFilters/Side.jsx
- src/components/views/Shop/SideFilters/SideStyle.module.css
> cardCss[fix]

- src/components/common/Menu/Menu.jsx
- src/components/views/Shop/Filters/Filters.jsx
- src/components/views/Shop/Filters/Filters.module.css
- src/components/views/Shop/Products/Products.jsx
- src/redux/productActions.js
- src/redux/productSlice.js
se muestran los filtros por marca y por subcategorias seleccionados y correccion de errores que se duplicaban los producst
> historial a la vista de filtros usados

- src/components/views/Shop/Filters/Filters.jsx
- src/components/views/Shop/Filters/Filters.module.css
- src/components/views/Shop/Products/Products.jsx
> correccion de error una llave demas

- src/components/common/Modals/ModalCart/ModalCart.jsx
- src/components/views/Home/Home.jsx
- src/components/views/Shop/Detail/Detail.jsx
- src/redux/productActions.js
- src/redux/productSlice.js
boton que dirige al detail de las cards en el carrusel
> detailCarousels

- src/components/views/Shop/Filters/Filters.jsx
- src/components/views/Shop/Filters/Filters.module.css
- src/components/views/Shop/Paginado/Paginado.jsx
- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/SideFilters/Side.jsx
- src/components/views/Shop/SideFilters/SideStyle.module.css
- src/redux/productActions.js
- src/redux/productSlice.js
se ve cuantas paginas tienes disponible, se tiran acordeones solo de 20 checkboxs, los acordeones vienen cerrados y solo se mantiene abierto 1. acordeon ordenado de A-Z
> listo paginado y filtros de marcas

- src/components/views/Home/Home.jsx
- src/redux/productActions.js
- src/redux/productSlice.js
ya los links "ver mas" de los carruseles redirigen a /shop y muestran los productos
> [FIXED] carousel routes

- src/App.js
- src/components/views/Cart/Cart.jsx
- src/components/views/CartProducts/CartProducts.jsx
- src/components/views/Home/Home.jsx
- src/components/views/Shop/Detail/Detail.jsx
- src/components/views/Shop/Detail/Detail.module.css
- src/components/views/Shop/Products/Products.jsx
- src/redux/CartActions.js
- src/redux/CartSlice.js
- src/redux/store.js
- redux del carrito
- todos los botones que tienen que añadir al carrito, ya añaden
- renderizo en la ruta /cart los productos que estan en el carrito
> [CREATE CART]

- src/components/views/About/About.jsx
se almacenan los datos en el local storage al llenar el formulario para que haya persistencia y cuando se envia se vacia el local storage
> persistencia en formulario contacto

- package-lock.json
- package.json
- src/components/Admin/Form/Form.jsx
> [FEATURE] claudinary

- src/components/Admin/Form/Form.jsx
- src/components/views/About/About.jsx
- src/components/views/Arrepentimiento/Arrepentimiento.jsx
cuando intentas subir un producto y recargas, siempre tiene la info guardada y cuando culminas y aprietas el boton, deshace el LS para que puedas cargar otro producto
> persistencia al intentar subir un producto

- src/components/views/CartProducts/CartProducts.jsx
- src/components/views/Shop/Products/Products.jsx
- src/redux/CartActions.js
- src/redux/CartSlice.js
si no tienes na en el carrito pero tu local storage si tiene en el carrito TE LO METE TO !!!!
> carrito con persistencia

- src/components/views/CartProducts/CartProducts.jsx
Reverts MoralesMatiasEzequiel/pf-libreria-FRONT#107
> Revert "fixed array"

- src/components/views/About/About.module.css
- src/components/views/Arrepentimiento/Arrepentimiento.jsx
- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/Shop.jsx
- src/components/views/Shop/Shop.module.css
- src/components/views/Shop/SideFilters/SideStyle.module.css
fix de pagination(ahora esta en shop)
fix de sidebar
quito pagination de products
> shop-sidebar-pagination[fix]

- src/components/views/Shop/Products/Products.jsx
VA CON EL ERROR DE LUCAS, 
al añadir te marca que está añadido al carrito y no te deja añadir 2 veces.....
> al añadir, te marca añadido

- src/components/views/Shop/Detail/Detail.jsx
desde el detail se ve si está en el carrito o si no está te deja añadirlo y luego te dice que "ya está "
> detail con add al carrito dinamico

- src/components/views/Shop/Detail/Detail.jsx
anda como messi PAPAAAAAA !!!!!!!!!!!!
> me faltó un codigo pa que andara al 100

- src/components/views/Cart/FormInfoCart.jsx
- src/components/views/Cart/FormShipmentCart.jsx
persistencia en los formularios de compra
> secso en los formularios de compra

- src/components/views/Home/Home.jsx
- src/components/views/Shop/Products/Products.jsx
- src/redux/productActions.js
- src/redux/productSlice.js
puedes hacer f5 las veces que te da la gana y nunca vas a perder la vista de los productos
> persistencia en la tienda

- src/index.js
> deploy 1.0

- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/SideFilters/Side.jsx
- src/redux/productSlice.js
ya prueba el searchbar y hacer f5 donde vos querás ...... lcdtm
> resolvido bug traedera de products

- src/components/views/Home/CarouselComments/CarouselComments.jsx
- src/components/views/Home/CarouselRating/CarouselRating.jsx
- src/components/views/Home/CarouselRating/CarouselRating.module.css
- src/components/views/Home/CarouselSale/CarouselSale.jsx
- src/components/views/Home/CarouselSale/CarouselSale.module.css
- src/components/views/Home/Home.jsx
> [FIXED] carruseles modularizados

- src/components/common/Nav/Nav.jsx
- src/components/common/Nav/Nav.module.css
cambié para que se vea la minitatura de la foto de usuario en el nav una vez logueado en vez de "Perfil", faltaría darle estilos bien para que no quede corrida, y estaría bueno que cuando está active tenga un reborde del mismo color en que se ponen los nav en active
> profile thumbnail

- src/App.js
- src/components/common/FormCreateReview/FormCreateReview.jsx
- src/components/views/Home/CarouselComments/CarouselComments.jsx
- src/components/views/Home/CarouselComments/CarouselComments.module.css
- src/components/views/Home/CarouselRating/CarouselRating.jsx
- src/components/views/Home/CarouselRating/CarouselRating.module.css
- src/components/views/Home/CarouselSale/CarouselSale.jsx
- src/components/views/Home/CarouselSale/CarouselSale.module.css
- src/components/views/Home/Home.jsx
- src/redux/ReviewsActions.js
- src/redux/ReviewsSlice.js
- src/redux/store.js
- redux para las reviews
- hacer carrusel de reviews, falta estilos
> get reviews

- src/App.js
- src/components/views/Favorites/Favorites.jsx
- src/components/views/Favs.jsx
- src/components/views/Profile/Profile.jsx
- src/components/views/Shop/Detail/Detail.jsx
- src/redux/favoriteActions.js
- src/redux/favoriteSlice.js
-add favoritePage
-add favorite function in details
-add favorite path
-add clear reducer from favorites
-persistencia de datos en favoritos
> favoritePage[feature]

- src/components/common/Menu/Menu.module.css
> navcolor[FIX]

- src/components/views/About/About.jsx
- src/components/views/About/About.module.css
- src/components/views/Arrepentimiento/Arrepentimiento.jsx
unificacion de acciones y estilos
> forms[FIX]

- src/components/common/Modals/ModalCart/ModalCart.jsx
add product.salePrice si el producto esta en descuento
> productPrice[fix]

- src/components/views/Favorites/Favorites.jsx
- src/components/views/Home/CarouselComments/CarouselComments.module.css
- src/components/views/Home/CarouselRating/CarouselRating.jsx
- src/components/views/Home/CarouselRating/CarouselRating.module.css
- src/components/views/Home/CarouselSale/CarouselSale.jsx
- src/components/views/Home/CarouselSale/CarouselSale.module.css
- src/components/views/Shop/Products/Products.jsx
- src/components/views/Shop/Products/Products.module.css
> styles[FIXES]
